author: NeilSun # 作者
description: NeilSun's blog
keyword: hexo-theme, vuejs

excerpt_link: Read more
logo: https://avatars.githubusercontent.com/u/18653098?s=400&u=8b3b494cfa224eb388a933aa9af8ac5e5b65b3f8&v=4
menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set utterances, gitment, uyan or disqus
# comment: utterances

# utterances config
# utterances_repo:                # e.g. GitHubAccount/RepoForUtterances
# utterances_issue_term: pathname # you can see other available options at 'https://utteranc.es/'
# utterances_theme: github-light  # you can see other available options at 'https://utteranc.es/'

# gitment config
# gitment_owner: yanm1ng
# gitment_repo: yanm1ng.github.io
# gitment_oauth_id: 0f87e490e00ee3fd87ef
# gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 
google_analytics: 
# disqus config
disqus_shortname: 

about: 
  banner: ""
  avatar: https://avatars.githubusercontent.com/u/18653098?s=400&u=8b3b494cfa224eb388a933aa9af8ac5e5b65b3f8&v=4
  description: "NeilSun's blog."
  # weibo_username: yanm1ng
  # twitter_username: yanm1ng
  # github_username: yanm1ng
  # zhihu_username: yummy1121
  # douban_username: yanm1ng
  # linkedin_username: 

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Local Search Support
local_search:
  enable: false